### ISSUE TITLE
Static analysis doesn't work

### ISSUE THREAD

**Issue by jooohny** [myfreeweb/eslint-plugin-pug#11]
Hello! Can you please help me with `eslint-plugin-pug`? It only highlights problems when eslint is run via CI, like: `./node_modules/.bin/eslint --ext .js,.pug .`
However, when I simply open _.pug_ files, is doesn't highlight anything and problems don't appear in  **PROBLEMS** tab of terminal.
I wonder if problem is on my side.

My .eslintrc.json file:
```
{
    "parser": "babel-eslint",
    "plugins": [
        "pug"
    ],
    "extends": [
        "airbnb-base",
        "plugin:node/recommended",
        "plugin:import/recommended",
        "plugin:prettier/recommended"
    ],
    "ignorePatterns": [
        "node_modules/**"
    ],
    "rules": {
        "prettier/prettier": "error",
        "no-console": "warn",
        "no-unused-vars": "warn",
        "global-require": "off",
        "import/no-dynamic-require": "off",
        "no-plusplus":  ["error", { "allowForLoopAfterthoughts": true }],
        "no-restricted-syntax": "off",
        "guard-for-in": "off"
    }
}

```

**Comment by valpackett** [comment]
Looks like your editor integration / language server should be configured to also react to `.pug` files?

**Comment by jooohny** [comment]
I'm trying to figure out the way of doing it for like several hours. No results. I'm using VS Code. Maybe you can guide me, please?

**Comment by jooohny** [comment]
I got it. Thanks!
