### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jooohny** [myfreeweb/eslint-plugin-pug#12]
The error occurs when using plugin. What could that be about?

```
Oops! Something went wrong! :(

ESLint: 7.26.0

TypeError: Cannot read property '0' of undefined
    at Object.exports.transformFix (D:\Dev\Nevosoft\ubs3\node_modules\eslint-plugin-pug\utils.js:117:72)
    at D:\Dev\Nevosoft\ubs3\node_modules\eslint-plugin-pug\utils.js:137:25
    at arrayEach (D:\Dev\Nevosoft\ubs3\node_modules\lodash\lodash.js:530:11)
    at Function.forEach (D:\Dev\Nevosoft\ubs3\node_modules\lodash\lodash.js:9410:14)
    at D:\Dev\Nevosoft\ubs3\node_modules\eslint-plugin-pug\utils.js:130:7
    at arrayEach (D:\Dev\Nevosoft\ubs3\node_modules\lodash\lodash.js:530:11)
    at Function.forEach (D:\Dev\Nevosoft\ubs3\node_modules\lodash\lodash.js:9410:14)
    at exports.postprocess (D:\Dev\Nevosoft\ubs3\node_modules\eslint-plugin-pug\utils.js:128:5)
    at Linter._verifyWithProcessor (D:\Dev\Nevosoft\ubs3\node_modules\eslint\lib\linter\linter.js:1329:16)
    at Linter._verifyWithConfigArray (D:\Dev\Nevosoft\ubs3\node_modules\eslint\lib\linter\linter.js:1266:25)
```

**Comment by valpackett** [comment]
Looks like you're using autofix, which is buggy here. Can you post a minimal example pug file that still crashes?

**Comment by jooohny** [comment]
```
link(
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous"
)
script(
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"
)
script(
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
    crossorigin="anonymous"
)
script.
    function tooltipInit() {
        const tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        const tooltipList = tooltipTriggerList.map((tooltipTriggerEl) => {
            return new bootstrap.Tooltip(tooltipTriggerEl);
        });
    }

```

**Comment by valpackett** [comment]
Hm, cannot reproduce, autofix has applied successfully:

```
% node_modules/eslint/bin/eslint.js --plugin pug --fix test/fixtures/bug.pug

/home/greg/src/github.com/unrelentingtech/eslint-plugin-pug/test/fixtures/bug.pug
  18:14  error  'tooltipInit' is defined but never used           no-unused-vars
  20:13  error  'tooltipList' is assigned a value but never used  no-unused-vars
  21:20  error  'bootstrap' is not defined                        no-undef
  23:6   error  Newline required at end of file but not found     eol-last

✖ 4 problems (4 errors, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

using ESLint v7.27.0

**Comment by taichunmin** [comment]
I think the issue is LF and CRLF problem.

```
"Expected linebreaks to be 'LF' but found 'CRLF'."
```

Because the plugin only fix js scripts in `.pug`, it will not change EOL of `.pug` file.

**Comment by jooohny** [comment]
Wow. [taichunmin](https://github.com/taichunmin) is right. So, what should I do about it? I'm using CRLF in this project.

**Comment by taichunmin** [comment]
you need to change the `.eslintrc.js` to ignore `linebreak-style` rule or set to CRLF.

**Comment by jooohny** [comment]
It helped in autofix. But running `./node_modules/.bin/eslint --ext .js,.pug .` still ends up with same error. I have main config in root directory and separate config in my folder with  **.pug** files where I include the plugin separately.

**Comment by taichunmin** [comment]
you can use multiple `.eslintrc.js` to override eslint setting like my repo: https://github.com/taichunmin/pug/blob/master/src/.eslintrc.js

**Comment by jooohny** [comment]
It's been broken again..I'm also using Prettier. And it also controls eol's. So when I'm using Prettier rule `"endOfLine": "crlf"`, the error occurs. If I delete that rule, the error disappears. But Prettier demands me to delete all `'cr'`s then. Defining eslint rule `"linebreak-style": "off"` doesn't help.

**Comment by jooohny** [comment]
Probably I also need Prettier pug plugin. I used to have it installed and I seemed to get some problems rather than any help. And also with 'lf's it worked good without it.

**Comment by jooohny** [comment]
I've created test project with minimal settings and files - the same problem occurs. Please, check it [here](https://github.com/jooohny/esllint-pug-test).

**Comment by taichunmin** [comment]
I tried to fix this issue with v1.2.4. Can @jooohny try again?

**Comment by jooohny** [comment]
@taichunmin Seems to be working. Thank you! 
Also there is that message from Prettier requiring `eol` at the end of file despite the fact that it is there. Don't you know where it comes from and how to fix it? [Picture](https://i.imgur.com/JMfpUi6.png)

**Comment by taichunmin** [comment]
The `eslint-plugin-pug` plugin will extract the js code in pug file and passthrough to eslint. You can add the rule `rules: { 'eol-last': ['error', 'never'] }` in `.eslintrc.js`

**Comment by jooohny** [comment]
@taichunmin It comes from Prettier not Eslint. Adding that rule doesn't help..

**Comment by taichunmin** [comment]
Maybe you can report to https://github.com/prettier/prettier-vscode ?
