### ISSUE TITLE
"Unexpected token" when using include in script tag

### ISSUE THREAD

**Issue by BadIdeaException** [myfreeweb/eslint-plugin-pug#16]
The following construct causes a linting error: 
```
script
    include somescript.js
```

The error says: `Parsing error: Unexpected token somescript`.

Pug itself handles this fine.

**Comment by taichunmin** [comment]
Fixed in v1.2.5. Can @BadIdeaException try again?

**Comment by BadIdeaException** [comment]
Working now :+1: 

VERY quick fix, I must say!
