### ISSUE TITLE
Highlighting js errors in VS Code working incorrectly

### ISSUE THREAD

**Issue by believer-ufa** [myfreeweb/eslint-plugin-pug#4]
Hello and thanks for this library!

I have errors in checking JS code in my Pug templates.

![image](https://user-images.githubusercontent.com/801727/32857148-bf02019e-ca68-11e7-9bad-82ec3980eca7.png)

I described all details in [issue to VS Code ESLint plugin](https://github.com/Microsoft/vscode-eslint/issues/338) because think what error in it, but we realized that the root of the problem is somewhere else. Maybe in code in that plugin?

Please, can you read above issue and say you thoughts about it?

I use [Visual Studio Code](https://github.com/Microsoft/vscode) ide, [vscode-eslint](https://github.com/Microsoft/vscode-eslint) plugin, [eslint-plugin-pug](https://github.com/myfreeweb/eslint-plugin-pug) plugin.

You can try to play with linting js code in Pug files if you clone [this repository](https://github.com/believer-ufa/vscode-eslint-pug).

**Comment by valpackett** [comment]
Should be fixed now, try version 1.1.1.
