### ISSUE TITLE
Crashes messages while editing caused by indentation issues

### ISSUE THREAD

**Issue by yogesh-onlinerti** [myfreeweb/eslint-plugin-pug#9]
![image](https://user-images.githubusercontent.com/75349552/115583094-34af9780-a2e7-11eb-9a25-0ace4a570dde.png)
![image](https://user-images.githubusercontent.com/75349552/115583450-848e5e80-a2e7-11eb-9f6e-25ebc0e38367.png)
Crashes too often while editing pug file, i.e right after entering '.' to add element's class.  This is inevitable, as adding '.' after naming the class is impractical. Currently this is the only way to avoid such crashes . This is one of many such crashes.

**Comment by valpackett** [comment]
Do you really need to run ESLint continuously? Why not only run it on save?

**Comment by yogesh-onlinerti** [comment]
I'm having auto-save enabled (delay: 500ms). I can increase the delay to reduce the frequency of crashes, but that is not the ideal solution. Better to expose an option to ignore pug indentation errors/warnings and then these errors should be caught if the option is enabled .

**Comment by taichunmin** [comment]
This issue should be report to one of "pug-lexer", "pug-parser" or "pug-walk".
